apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mcp-gateway.fullname" . }}-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "mcp-gateway.fullname" . }}
            port:
              number: {{ .Values.service.port }}
